import './_env';
import { randomBytes } from 'node:crypto';
import { writeFileSync } from 'node:fs';
import { neon } from '@neondatabase/serverless';

/**
 * Creates a least-privilege database role for the running app.
 *
 *   pnpm db:app-role [output-file]
 *
 * The app was connecting as the database owner, which is more authority than it
 * uses. It only ever reads the index and writes chat history: it never creates a
 * table, and never writes to `pages`, `chunks`, `articles` or `settings` — those
 * belong to the ingest, which runs from a trusted machine.
 *
 * Splitting them means a compromise of the internet-facing container cannot
 * alter or drop the index, only the conversations. Migrations and ingest keep
 * using the owner credential, which never leaves a developer machine or CI.
 *
 * The generated password is written to a file and never printed.
 */

const ROLE = 'valheim_app';

/** Read-only: the index. Written by the ingest, never by the app. */
const READ_ONLY = ['pages', 'chunks', 'articles', 'settings', 'ingest_runs', 'locks'];

/** Read-write: everything the app itself creates. */
const READ_WRITE = ['conversations', 'messages', 'login_attempts', 'article_translations'];

const outputPath = process.argv[2] ?? '.app-role-url';

const ownerUrl = process.env.DATABASE_URL;
if (!ownerUrl) {
  console.error('DATABASE_URL must be set to the owner connection string.');
  process.exit(1);
}

const sql = neon(ownerUrl);
const password = randomBytes(24).toString('base64url');

// Neon roles are created through SQL like any Postgres role; the console picks
// them up. `NOINHERIT` is deliberate — this role should hold exactly what is
// granted to it and nothing acquired through membership.
const exists = await sql`SELECT 1 FROM pg_roles WHERE rolname = ${ROLE}`;

if (exists.length > 0) {
  await sql.query(`ALTER ROLE ${ROLE} WITH LOGIN NOINHERIT PASSWORD '${password}'`);
  console.log(`Role ${ROLE} already existed; its password was rotated.`);
} else {
  await sql.query(`CREATE ROLE ${ROLE} WITH LOGIN NOINHERIT PASSWORD '${password}'`);
  console.log(`Created role ${ROLE}.`);
}

const database = new URL(ownerUrl.replace('postgresql://', 'https://')).pathname.replace('/', '');
await sql.query(`GRANT CONNECT ON DATABASE "${database}" TO ${ROLE}`);
await sql.query(`GRANT USAGE ON SCHEMA public TO ${ROLE}`);

for (const table of READ_ONLY) {
  await sql.query(`GRANT SELECT ON TABLE public.${table} TO ${ROLE}`);
}
for (const table of READ_WRITE) {
  await sql.query(`GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.${table} TO ${ROLE}`);
}

// No sequences: every id in this schema is generated by the application.
console.log(`  read-only:  ${READ_ONLY.join(', ')}`);
console.log(`  read-write: ${READ_WRITE.join(', ')}`);

const url = new URL(ownerUrl.replace('postgresql://', 'https://'));
url.username = ROLE;
url.password = password;
const appUrl = url.toString().replace('https://', 'postgresql://');

writeFileSync(outputPath, `${appUrl}\n`, { mode: 0o600 });
console.log(`\nConnection string written to ${outputPath}. It was not printed.`);
console.log('Delete that file once the deployment has it.');
